site_name: Process Compose
site_url: https://github.com/F1bonacc1/process-compose
repo_url: https://github.com/F1bonacc1/process-compose
repo_name: process-compose
nav:
  - Home: index.md
  - Getting Started:
    - 'Quick Start': intro.md
    - Installation: installation.md
  - Documentation:
    - 'Processes Lifetime': launcher.md
    - Logger: logging.md
    - 'Health Checks': health.md
    - Configuration: configuration.md
    - 'Merging Configuration': merge.md
    - 'Remote Client': client.md
    - TUI: tui.md
  - CLI:
    - 'process-compose': cli/process-compose.md
    - 'attach': cli/process-compose_attach.md
    - 'completion': cli/process-compose_completion.md
    - 'down': cli/process-compose_down.md
    - 'info': cli/process-compose_info.md
    - 'process': cli/process-compose_process.md
    - 'project': cli/process-compose_project.md
    - 'run': cli/process-compose_run.md
    - 'up': cli/process-compose_up.md
    - 'version': cli/process-compose_version.md
  - Contributing:
    - Contributing: contributing.md
    - Sponsors: sponsors.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue-grey
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/f1bonacc1
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ProcessCompose
  analytics:
    provider: google
    property: G-MLY6JDXHNY

markdown_extensions:
  - toc:
      title: Table of contents
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/f1bonacc1"  target="_blank" rel="noopener">Eugene Berger</a>
