name: docs
on:
  push:
    branches:
      - main
      - docs
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg

      - name: Build docs
        if: ${{ github.event_name == 'pull_request' }}
        run: mkdocs build
        working-directory: ./www

      - name: Deploy docs to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        run: mkdocs gh-deploy --force
        working-directory: ./www
